### PR TITLE
Added ability to switch off monitor control, debug messages, additional notification

### PR DESCRIPTION
**Pull request by BrianHepler**
I took a shot at the requested functionality and this is what I came up with.
`controlDisplay`: turns on/off the module control of the monitor. Useful for a notification-only configuration.
`additionalNotification`: send a user-defined notification to other modules.
`dubug`: put log messages both in the electron and node console logs.

### CODE REVIEW

**Comment by BrianHepler** [comment]
Oh, and I deleted the package-lock.json file. That's generated by npm when you run the install process. Having it part of the repository will interfere with future upgrades and the auto-script by @sdetwil.

**Comment by rejas** [comment]
Thats a weird PR. What branch did you started from? And where is the stuff in there you mention, like additionalNotification ?

**Comment by rejas** [comment]
Please start from my develop branch and base your PR agaisnt that too.

**Comment by BrianHepler** [comment]
Will do.

**Pull request closed without merging**
